### PR TITLE
Upgrade to expo 47

### PR DESCRIPTION
**Pull request by snordmann**
Related to https://github.com/jellyfin/jellyfin-expo/issues/492

I am going to work on this PR in the next few days.

- [x] `npm install expo@47`
- [x] `npx expo install --fix`
- [ ] `npm run test` and make sure tests still work
- [x] Manual tests on simulated iOS

### CODE REVIEW

**Comment by snordmann** [comment]
damn expo got hands.

I tried now multiple things to update expo (well mainly expo-cli upgrade), and somehow the build or tests always break in unforeseen ways.

It'd be awesome, if somebody with familiarity in this codebase and/or expo could help me. Feel free to reach out to me!

**Comment by thornbill** [comment]
Yeah there are normally a few breaking changes in each version but the [release notes](https://blog.expo.dev/expo-sdk-47-a0f6f5c038af) typically document the needed changes pretty well.

**Comment by snordmann** [comment]
What I am currently wondering is: Do you just skip the dependency tree building in npm install with --force --legacy-peer-deps? It seems that most of the mobx dependencies expect react 16, but we are using react 18 already.

Is that normal? Should I npm install with --legacy-peer-deps enabled? How did you generate the package-lock?

**Comment by snordmann** [comment]
I have missed updating the devDependencies (esp. jest-expo to something that is compatible with version 47). After that upgrade I changed some of the snapshots to also include some new properties that are included (btw. I am now using npm install with the `--legacy-peer-deps` option).

The last error that I have a still pretty cryptic to me: `PrettyFormatPluginError: Invalid string lengthRangeError: Invalid string length`

This error is for the files:

* `components/__tests__/NativeShellWebView.test.js`
* `components/__tests__/RefreshWebView.test.js`
* `screens/__tests__/ErrorScreen.test.js`

I don't understand why only these test files (and snapshots) are affected. Is it because the snapshots are so small? Is is something else that differentiates these three tests from the others? I don't know, but I will find that out in the next week.

**Comment by snordmann** [comment]
I am closing this PR because #539 seems to make better progress (and I have learned, that expo is a beast that I cannot yet tame).

Good luck to enigma0Z and their effort to update to a new version :)

**Pull request closed without merging**
