### PR TITLE
Don't require full screen on iOS

### LINKED ISSUE #376: Split screen does not work on iPadOS 15
<p><strong>Describe the bug</strong></p>
<p>Split screen does not work on iPadOS 15</p>
<p><strong>System (please complete the following information):</strong></p>
<ul>
<li>iOS Version: 15.5</li>
<li>Jellyfin Expo version: 1.5.0</li>
<li>Jellyfin Server version: Any</li>
</ul>
<p><strong>To Reproduce</strong></p>
<ol>
<li>Open the app on an iPad </li>
</ol>
<p><strong>Expected behavior</strong>
Split screen should work as it did in iPadOS 14</p>

### LINKED ISSUE #426: Can't go fullscreen on external monitor
**Describe the bug**

M1 and better iPads support external monitors since iOS 16. Apps that support split screen can go full screen on the external monitor, other apps will be just displayed in the middle with the same size as the iPad's display.

**System (please complete the following information):**
 - iOS Version: 16.4
 - Jellyfin Expo version: 1.5.0
 - Jellyfin Server version: 10.8.9

**Additional context**

This value needs to be removed or set to false in the [info.plist](https://github.com/jellyfin/jellyfin-expo/blob/fcd9b0f1ec98250c8606fa0a9ccda478430125c5/app.json#L33): https://developer.apple.com/documentation/bundleresources/information_property_list/uirequiresfullscreen

I'm currently without a Mac for like 3 more weeks, I'll submit a PR once I can try it out myself if nobody else picks it up until then.

### PR DESCRIPTION
**Pull request by Cyberbeni**
fixes #426 
fixes #376

couldn't test it because the Expo Go app already supports split screen and couldn't figure out how to build the standalone app

### CODE REVIEW

**Comment by Cyberbeni** [comment]
Also fixes #376

**Review by anthonylavado — APPROVED** [review]

**Review by DAcodedBEAT — APPROVED** [review]

**Comment by thornbill** [comment]
I need to do some additional testing, but it doesn't _seem_ like this is needed in the updated version of Expo.

**Comment by Cyberbeni** [comment]
If I remember correctly if a new enough Expo version is specified in some config file then it is not needed. But if a newer Expo version is used for building but the config is not updated then it is needed.
Or maybe the config part is not needed, I don't know.
But when downloading "Expo Go" from the App Store then requiresFullScreen is set to false for that application and the config for the in-development application doesn't matter.

**Comment by Cyberbeni** [comment]
According to my comments on this issue, either sdkVersion or requireFullScreen is needed in app.json: https://github.com/jellyfin/jellyfin-expo/issues/426
The part I linked there is still unchanged in Expo's source code: https://github.com/expo/expo/blob/0a999ca61531f3064e589be623ff0d7f8247cebe/packages/%40expo/config-plugins/src/ios/RequiresFullScreen.ts#L23-L25

**Review by thornbill — APPROVED** [review]

**Pull request merged**
