### PR TITLE
Switch to npm

### PR DESCRIPTION
**Pull request by ferferga**
Follow up of https://github.com/jellyfin/jellyfin-vue/pull/815

*This needs further discussion across all the client devs, as this has been discussed more thoroughly between the Vue contributors, but not as much with the rest of the client developers and. Most client developers showed interest in switching to npm, however, no formal discussion has taken place and, ideally, we should use the same package manager everywhere*

Major reasons for switching:

* All the yarn's advantages over npm are non-existent today
* Yarn introduced some breaking changes in 2.x that caused controversies and avoid us to upgrade directly, which means we are stuck in a version in maintenance mode. So far, all the npm major updates could be updated like a charm, and it's likely they will commit to it. The same can't be said about yarn.
* Npm comes with the node installation, so it's frictionless for the user
* Npm is more mainstream and all the package maintainers add instructions with how to use it to install their packages. The same doesn't apply to yarn. Although adapting the commands to yarn is trivial, for new contributors it might cause some friction.

## Extra

* Added dependabot for dependency updates

### CODE REVIEW

**Comment by thornbill** [comment]
We discussed this in chat but so we don't lose track of it, adding dependabot to this project is going to be more complex because a lot of packages have to be managed with the Expo cli.

**Comment by ferferga** [comment]
Dependabot now only updates GH Actions as of last rebase 👍.

**Comment by ferferga** [comment]
Dependabot now only updates GH Actions as of last rebase 👍.

**Comment by ferferga** [comment]
Dependabot now only updates GH Actions as of last rebase 👍.

**Review by thornbill — APPROVED** [review]

**Pull request merged**
